// Landing Page Template Definitions
// 25 templates across 5 niches for affiliate marketers

export interface TemplateElement {
    id: string;
    type: 'background' | 'text' | 'media' | 'shape';
    // Background properties
    gradient?: {
        type: 'linear' | 'radial';
        angle?: number;
        colors: string[];
    };
    color?: string;
    // Text properties
    content?: string;
    contentType?: string;
    x?: number;
    y?: number;
    fontSize?: number;
    fontWeight?: string;
    fontFamily?: string;
    textAlign?: 'left' | 'center' | 'right';
    maxWidth?: number;
    lineHeight?: number;
    // Media properties
    mediaType?: 'image' | 'video' | null;
    url?: string | null;
    posterFrame?: string | null;
    placeholder?: string;
    acceptTypes?: ('image' | 'video')[];
    // Shape properties
    shape?: 'rect' | 'roundedRect' | 'circle';
    width?: number;
    height?: number;
    cornerRadius?: number;
    // Common properties
    editable: boolean;
    editLabel?: string;
    suggestedContent?: string[];
    shadow?: {
        blur: number;
        color: string;
        offsetX?: number;
        offsetY?: number;
    };
}

export interface LandingPageTemplate {
    id: string;
    name: string;
    category: 'saas' | 'ecommerce' | 'coaching' | 'agency' | 'leadmagnet';
    size: { width: number; height: number };
    thumbnail: string;
    description: string;
    elements: TemplateElement[];
}

export const LANDING_PAGE_TEMPLATES: LandingPageTemplate[] = [
    // ========================================
    // SAAS TEMPLATES (5)
    // ========================================
    {
        id: 'saas-hero-bold',
        name: 'Bold Hero',
        category: 'saas',
        size: { width: 1920, height: 1080 },
        thumbnail: '💼',
        description: 'Modern hero section with product showcase',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#0F172A', '#1E293B'],
                },
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'Ship Faster with AI-Powered Tools',
                contentType: 'headline',
                x: 100,
                y: 150,
                fontSize: 64,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                maxWidth: 800,
                editable: true,
                editLabel: '📝 Main Headline',
                suggestedContent: ['headline', 'value_proposition'],
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Build, test, and deploy in minutes instead of days',
                contentType: 'subheadline',
                x: 100,
                y: 280,
                fontSize: 28,
                fontFamily: 'Arial',
                color: '#94A3B8',
                maxWidth: 700,
                editable: true,
                editLabel: '📝 Subheadline',
                suggestedContent: ['subheadline', 'description'],
            },
            {
                id: 'cta-bg-1',
                type: 'shape',
                shape: 'roundedRect',
                x: 100,
                y: 380,
                width: 220,
                height: 60,
                color: '#3B82F6',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'cta-text-1',
                type: 'text',
                content: 'Start Free Trial',
                contentType: 'cta',
                x: 210,
                y: 410,
                fontSize: 18,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 CTA Button',
                suggestedContent: ['cta', 'button_text'],
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                posterFrame: null,
                placeholder: 'Product Screenshot or Demo Video',
                x: 1000,
                y: 150,
                width: 800,
                height: 600,
                cornerRadius: 12,
                editable: true,
                editLabel: '🎥 Product Media',
                acceptTypes: ['image', 'video'],
                shadow: {
                    blur: 40,
                    color: 'rgba(0,0,0,0.3)',
                    offsetY: 20,
                },
            },
        ],
    },
    {
        id: 'saas-features',
        name: 'Features Grid',
        category: 'saas',
        size: { width: 1920, height: 1080 },
        thumbnail: '🎯',
        description: '3-column feature showcase',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#F8FAFC',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Everything You Need to Succeed',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Section Title',
            },
            {
                id: 'feature-1-icon',
                type: 'text',
                content: '⚡',
                x: 350,
                y: 300,
                fontSize: 64,
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'feature-1-title',
                type: 'text',
                content: 'Lightning Fast',
                x: 350,
                y: 400,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                maxWidth: 300,
                editable: true,
                editLabel: '📝 Feature 1 Title',
            },
            {
                id: 'feature-1-desc',
                type: 'text',
                content: 'Deploy in seconds, not hours',
                x: 350,
                y: 450,
                fontSize: 16,
                fontFamily: 'Arial',
                color: '#64748B',
                textAlign: 'center',
                maxWidth: 300,
                editable: true,
                editLabel: '📝 Feature 1 Description',
            },
            {
                id: 'feature-2-icon',
                type: 'text',
                content: '🔒',
                x: 960,
                y: 300,
                fontSize: 64,
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'feature-2-title',
                type: 'text',
                content: 'Enterprise Security',
                x: 960,
                y: 400,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                maxWidth: 300,
                editable: true,
                editLabel: '📝 Feature 2 Title',
            },
            {
                id: 'feature-2-desc',
                type: 'text',
                content: 'Bank-level encryption & compliance',
                x: 960,
                y: 450,
                fontSize: 16,
                fontFamily: 'Arial',
                color: '#64748B',
                textAlign: 'center',
                maxWidth: 300,
                editable: true,
                editLabel: '📝 Feature 2 Description',
            },
            {
                id: 'feature-3-icon',
                type: 'text',
                content: '☁️',
                x: 1570,
                y: 300,
                fontSize: 64,
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'feature-3-title',
                type: 'text',
                content: 'Cloud Native',
                x: 1570,
                y: 400,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                maxWidth: 300,
                editable: true,
                editLabel: '📝 Feature 3 Title',
            },
            {
                id: 'feature-3-desc',
                type: 'text',
                content: 'Scale infinitely with zero maintenance',
                x: 1570,
                y: 450,
                fontSize: 16,
                fontFamily: 'Arial',
                color: '#64748B',
                textAlign: 'center',
                maxWidth: 300,
                editable: true,
                editLabel: '📝 Feature 3 Description',
            },
        ],
    },
    {
        id: 'saas-pricing',
        name: 'Pricing Table',
        category: 'saas',
        size: { width: 1920, height: 1080 },
        thumbnail: '💰',
        description: 'Side-by-side pricing comparison',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 180,
                    colors: ['#FFFFFF', '#F1F5F9'],
                },
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Simple, Transparent Pricing',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Pricing Title',
            },
            // Starter Plan
            {
                id: 'plan-1-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 400,
                y: 250,
                width: 400,
                height: 600,
                color: '#FFFFFF',
                cornerRadius: 16,
                editable: false,
                shadow: { blur: 20, color: 'rgba(0,0,0,0.1)' },
            },
            {
                id: 'plan-1-name',
                type: 'text',
                content: 'Starter',
                x: 600,
                y: 320,
                fontSize: 28,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Plan 1 Name',
            },
            {
                id: 'plan-1-price',
                type: 'text',
                content: '$49/mo',
                x: 600,
                y: 380,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#3B82F6',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Plan 1 Price',
            },
            // Pro Plan (Featured)
            {
                id: 'plan-2-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 860,
                y: 200,
                width: 400,
                height: 700,
                color: '#3B82F6',
                cornerRadius: 16,
                editable: false,
                shadow: { blur: 30, color: 'rgba(59,130,246,0.3)' },
            },
            {
                id: 'plan-2-badge',
                type: 'text',
                content: 'MOST POPULAR',
                x: 1060,
                y: 250,
                fontSize: 14,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FCD34D',
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'plan-2-name',
                type: 'text',
                content: 'Professional',
                x: 1060,
                y: 300,
                fontSize: 28,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Plan 2 Name',
            },
            {
                id: 'plan-2-price',
                type: 'text',
                content: '$99/mo',
                x: 1060,
                y: 360,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Plan 2 Price',
            },
        ],
    },
    {
        id: 'saas-demo',
        name: 'Demo Request',
        category: 'saas',
        size: { width: 1920, height: 1080 },
        thumbnail: '🎬',
        description: 'Demo video with CTA',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#6366F1', '#8B5CF6'],
                },
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'See It In Action',
                x: 960,
                y: 150,
                fontSize: 64,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Demo Video',
                x: 560,
                y: 300,
                width: 800,
                height: 450,
                cornerRadius: 16,
                editable: true,
                editLabel: '🎥 Demo Video',
                acceptTypes: ['video', 'image'],
                shadow: { blur: 60, color: 'rgba(0,0,0,0.4)' },
            },
            {
                id: 'cta-bg-1',
                type: 'shape',
                shape: 'roundedRect',
                x: 810,
                y: 850,
                width: 300,
                height: 70,
                color: '#FFFFFF',
                cornerRadius: 35,
                editable: false,
            },
            {
                id: 'cta-text-1',
                type: 'text',
                content: 'Request Demo',
                x: 960,
                y: 885,
                fontSize: 20,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#6366F1',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 CTA',
            },
        ],
    },
    {
        id: 'saas-testimonials',
        name: 'Testimonials',
        category: 'saas',
        size: { width: 1920, height: 1080 },
        thumbnail: '⭐',
        description: 'Customer quotes with video',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#0F172A',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Trusted by 10,000+ Companies',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Customer Testimonial Video',
                x: 260,
                y: 250,
                width: 600,
                height: 400,
                cornerRadius: 12,
                editable: true,
                editLabel: '🎥 Testimonial Video',
                acceptTypes: ['video', 'image'],
            },
            {
                id: 'quote-1',
                type: 'text',
                content: '"This tool saved us 20 hours per week. Game changer for our team!"',
                x: 1000,
                y: 350,
                fontSize: 32,
                fontFamily: 'Arial',
                color: '#E2E8F0',
                maxWidth: 700,
                lineHeight: 1.5,
                editable: true,
                editLabel: '📝 Testimonial Quote',
            },
            {
                id: 'author-1',
                type: 'text',
                content: '— Sarah Johnson, CEO at TechCorp',
                x: 1000,
                y: 550,
                fontSize: 18,
                fontFamily: 'Arial',
                color: '#94A3B8',
                editable: true,
                editLabel: '📝 Author',
            },
        ],
    },

    // ========================================
    // E-COMMERCE TEMPLATES (5)
    // ========================================
    {
        id: 'ecom-product-hero',
        name: 'Product Hero',
        category: 'ecommerce',
        size: { width: 1920, height: 1080 },
        thumbnail: '🛍️',
        description: 'Lifestyle product showcase',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#F8FAFC',
                editable: false,
            },
            {
                id: 'product-name',
                type: 'text',
                content: 'Premium Wireless Headphones',
                x: 100,
                y: 200,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                editable: true,
                editLabel: '📝 Product Name',
            },
            {
                id: 'price',
                type: 'text',
                content: '$299',
                x: 100,
                y: 300,
                fontSize: 48,
                fontFamily: 'Arial',
                color: '#3B82F6',
                editable: true,
                editLabel: '📝 Price',
            },
            {
                id: 'description',
                type: 'text',
                content: 'Studio-quality sound with active noise cancellation',
                x: 100,
                y: 380,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#64748B',
                maxWidth: 600,
                editable: true,
                editLabel: '📝 Description',
            },
            {
                id: 'cta-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 100,
                y: 500,
                width: 180,
                height: 60,
                color: '#0F172A',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'cta-text',
                type: 'text',
                content: 'Buy Now',
                x: 190,
                y: 530,
                fontSize: 18,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 CTA',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Product Photo or 360° Video',
                x: 900,
                y: 100,
                width: 900,
                height: 900,
                editable: true,
                editLabel: '🎥 Product Media',
                acceptTypes: ['image', 'video'],
            },
        ],
    },
    {
        id: 'ecom-category',
        name: 'Category Grid',
        category: 'ecommerce',
        size: { width: 1920, height: 1080 },
        thumbnail: '📦',
        description: 'Multi-product showcase',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#FFFFFF',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'New Arrivals',
                x: 960,
                y: 100,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Collection Title',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Product 1',
                x: 200,
                y: 250,
                width: 400,
                height: 400,
                cornerRadius: 8,
                editable: true,
                editLabel: '🎥 Product 1',
                acceptTypes: ['image', 'video'],
            },
            {
                id: 'media-2',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Product 2',
                x: 760,
                y: 250,
                width: 400,
                height: 400,
                cornerRadius: 8,
                editable: true,
                editLabel: '🎥 Product 2',
                acceptTypes: ['image', 'video'],
            },
            {
                id: 'media-3',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Product 3',
                x: 1320,
                y: 250,
                width: 400,
                height: 400,
                cornerRadius: 8,
                editable: true,
                editLabel: '🎥 Product 3',
                acceptTypes: ['image', 'video'],
            },
        ],
    },
    {
        id: 'ecom-sale',
        name: 'Sale Banner',
        category: 'ecommerce',
        size: { width: 1920, height: 600 },
        thumbnail: '🔥',
        description: 'Limited time offer',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 90,
                    colors: ['#DC2626', '#B91C1C'],
                },
                editable: false,
            },
            {
                id: 'badge',
                type: 'text',
                content: '🔥 SALE',
                x: 960,
                y: 100,
                fontSize: 32,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FEF3C7',
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'headline',
                type: 'text',
                content: '50% OFF Everything',
                x: 960,
                y: 200,
                fontSize: 72,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Sale Headline',
            },
            {
                id: 'subheadline',
                type: 'text',
                content: 'Limited Time Only • Ends Sunday',
                x: 960,
                y: 320,
                fontSize: 28,
                fontFamily: 'Arial',
                color: '#FEE2E2',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Urgency Message',
            },
            {
                id: 'cta-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 810,
                y: 420,
                width: 300,
                height: 70,
                color: '#FFFFFF',
                cornerRadius: 35,
                editable: false,
            },
            {
                id: 'cta-text',
                type: 'text',
                content: 'Shop Now',
                x: 960,
                y: 455,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#DC2626',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 CTA',
            },
        ],
    },
    {
        id: 'ecom-brand',
        name: 'Brand Story',
        category: 'ecommerce',
        size: { width: 1920, height: 1080 },
        thumbnail: '✨',
        description: 'About section with founder video',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#FEF7ED',
                editable: false,
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Founder Story Video',
                x: 200,
                y: 200,
                width: 700,
                height: 700,
                cornerRadius: 16,
                editable: true,
                editLabel: '🎥 Founder Video',
                acceptTypes: ['video', 'image'],
            },
            {
                id: 'title',
                type: 'text',
                content: 'Handcrafted with Love',
                x: 1050,
                y: 300,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#78350F',
                maxWidth: 700,
                editable: true,
                editLabel: '📝 Brand Title',
            },
            {
                id: 'story',
                type: 'text',
                content: 'Every piece is carefully crafted by artisans who pour their heart into their work.',
                x: 1050,
                y: 400,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#92400E',
                maxWidth: 700,
                lineHeight: 1.6,
                editable: true,
                editLabel: '📝 Brand Story',
            },
        ],
    },
    {
        id: 'ecom-comparison',
        name: 'Product Compare',
        category: 'ecommerce',
        size: { width: 1920, height: 1080 },
        thumbnail: '⚖️',
        description: 'Side-by-side comparison',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#F1F5F9',
                editable: false,
            },
            {
                id: 'title',
                type: 'text',
                content: 'Choose Your Perfect Fit',
                x: 960,
                y: 80,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Product A',
                x: 300,
                y: 250,
                width: 500,
                height: 500,
                editable: true,
                editLabel: '🎥 Product A',
                acceptTypes: ['image', 'video'],
            },
            {
                id: 'product-1-name',
                type: 'text',
                content: 'Standard Edition',
                x: 550,
                y: 800,
                fontSize: 32,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Product A Name',
            },
            {
                id: 'media-2',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Product B',
                x: 1120,
                y: 250,
                width: 500,
                height: 500,
                editable: true,
                editLabel: '🎥 Product B',
                acceptTypes: ['image', 'video'],
            },
            {
                id: 'product-2-name',
                type: 'text',
                content: 'Premium Edition',
                x: 1370,
                y: 800,
                fontSize: 32,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Product B Name',
            },
        ],
    },

    // ========================================
    // COACHING TEMPLATES (5)
    // ========================================
    {
        id: 'coach-hero',
        name: 'Coach Hero',
        category: 'coaching',
        size: { width: 1920, height: 1080 },
        thumbnail: '🎓',
        description: 'Personal transformation with coach photo',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#7C3AED', '#C026D3'],
                },
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'Unlock Your Potential',
                x: 100,
                y: 150,
                fontSize: 64,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                maxWidth: 800,
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Work 1-on-1 with a certified life coach',
                x: 100,
                y: 280,
                fontSize: 28,
                fontFamily: 'Arial',
                color: '#E9D5FF',
                maxWidth: 700,
                editable: true,
                editLabel: '📝 Subheadline',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Coach Photo',
                x: 1000,
                y: 150,
                width: 800,
                height: 600,
                cornerRadius: 400,
                editable: true,
                editLabel: '🎥 Coach Photo',
                acceptTypes: ['image'],
            },
        ],
    },
    {
        id: 'coach-results',
        name: 'Client Results',
        category: 'coaching',
        size: { width: 1920, height: 1080 },
        thumbnail: '📊',
        description: 'Before/after transformations',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#F9FAFB',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Real Results from Real Clients',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Client Before',
                x: 400,
                y: 250,
                width: 400,
                height: 400,
                cornerRadius: 8,
                editable: true,
                editLabel: '🎥 Before Photo',
                acceptTypes: ['image'],
            },
            {
                id: 'media-2',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Client After',
                x: 1120,
                y: 250,
                width: 400,
                height: 400,
                cornerRadius: 8,
                editable: true,
                editLabel: '🎥 After Photo',
                acceptTypes: ['image'],
            },
        ],
    },
    {
        id: 'coach-testimonials',
        name: 'Success Stories',
        category: 'coaching',
        size: { width: 1920, height: 1080 },
        thumbnail: '💬',
        description: 'Video testimonials from clients',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#1F2937',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'What My Clients Say',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'quote-1',
                type: 'text',
                content: '"Working with Sarah changed my life completely. I got promoted and doubled my income!"',
                x: 960,
                y: 400,
                fontSize: 32,
                fontFamily: 'Arial',
                color: '#E5E7EB',
                maxWidth: 900,
                lineHeight: 1.5,
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Testimonial',
            },
        ],
    },
    {
        id: 'coach-programs',
        name: 'Coaching Programs',
        category: 'coaching',
        size: { width: 1920, height: 1080 },
        thumbnail: '📋',
        description: 'Different coaching package options',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#FFFFFF',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Choose Your Coaching Path',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'program-1',
                type: 'text',
                content: '1 Month Intensive\n$2,000',
                x: 300,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Program 1',
            },
            {
                id: 'program-2',
                type: 'text',
                content: '3 Month Transformation\n$5,000',
                x: 900,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Program 2',
            },
            {
                id: 'program-3',
                type: 'text',
                content: '6 Month Mastery\n$9,000',
                x: 1500,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Program 3',
            },
        ],
    },
    {
        id: 'coach-cta',
        name: 'Book Session',
        category: 'coaching',
        size: { width: 1920, height: 1080 },
        thumbnail: '📅',
        description: 'Free consultation booking',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#F59E0B', '#EF4444'],
                },
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'Ready to Transform Your Life?',
                x: 960,
                y: 250,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Book a FREE 30-minute strategy session',
                x: 960,
                y: 400,
                fontSize: 32,
                fontFamily: 'Arial',
                color: '#FEF3C7',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Subheadline',
            },
            {
                id: 'email-form-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 660,
                y: 550,
                width: 600,
                height: 140,
                color: '#FFFFFF',
                cornerRadius: 12,
                editable: false,
                shadow: { blur: 20, color: 'rgba(0,0,0,0.2)' },
            },
            {
                id: 'email-field-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 580,
                width: 520,
                height: 50,
                color: '#F3F4F6',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'email-placeholder',
                type: 'text',
                content: 'Your email address...',
                x: 720,
                y: 605,
                fontSize: 18,
                fontFamily: 'Arial',
                color: '#9CA3AF',
                editable: true,
                editLabel: '📝 Email Placeholder',
            },
            {
                id: 'submit-btn-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 650,
                width: 520,
                height: 50,
                color: '#F59E0B',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'submit-btn-text',
                type: 'text',
                content: 'Book My Free Session',
                x: 960,
                y: 675,
                fontSize: 18,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Submit Button Text',
            },
        ],
    },

    // ========================================
    // AGENCY TEMPLATES (5)
    // ========================================
    {
        id: 'agency-portfolio',
        name: 'Portfolio Showcase',
        category: 'agency',
        size: { width: 1920, height: 1080 },
        thumbnail: '🎨',
        description: 'Featured work examples',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#F8FAFC',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Our Latest Work',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'media-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Project 1',
                x: 200,
                y: 250,
                width: 500,
                height: 350,
                editable: true,
                editLabel: '🎥 Project 1',
                acceptTypes: ['image'],
            },
            {
                id: 'media-2',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Project 2',
                x: 1220,
                y: 250,
                width: 500,
                height: 350,
                editable: true,
                editLabel: '🎥 Project 2',
                acceptTypes: ['image'],
            },
        ],
    },
    {
        id: 'agency-services',
        name: 'Service Packages',
        category: 'agency',
        size: { width: 1920, height: 1080 },
        thumbnail: '🛠️',
        description: 'What we offer to clients',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#FFFFFF',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Our Services',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'service-1',
                type: 'text',
                content: '🎨 Branding\nStrategy & Identity',
                x: 300,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Service 1',
            },
            {
                id: 'service-2',
                type: 'text',
                content: '💻 Web Design\nModern & Responsive',
                x: 900,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Service 2',
            },
            {
                id: 'service-3',
                type: 'text',
                content: '📱 Mobile Apps\niOS & Android',
                x: 1500,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Service 3',
            },
        ],
    },
    {
        id: 'agency-team',
        name: 'Meet the Team',
        category: 'agency',
        size: { width: 1920, height: 1080 },
        thumbnail: '👥',
        description: 'Team member profiles',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#1F2937',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Meet Our Team',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'member-1',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Team Member 1',
                x: 400,
                y: 250,
                width: 300,
                height: 300,
                cornerRadius: 150,
                editable: true,
                editLabel: '🎥 Member 1',
                acceptTypes: ['image'],
            },
            {
                id: 'member-2',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Team Member 2',
                x: 810,
                y: 250,
                width: 300,
                height: 300,
                cornerRadius: 150,
                editable: true,
                editLabel: '🎥 Member 2',
                acceptTypes: ['image'],
            },
            {
                id: 'member-3',
                type: 'media',
                mediaType: null,
                url: null,
                placeholder: 'Team Member 3',
                x: 1220,
                y: 250,
                width: 300,
                height: 300,
                cornerRadius: 150,
                editable: true,
                editLabel: '🎥 Member 3',
                acceptTypes: ['image'],
            },
        ],
    },
    {
        id: 'agency-process',
        name: 'Our Process',
        category: 'agency',
        size: { width: 1920, height: 1080 },
        thumbnail: '⚙️',
        description: 'How we work with clients',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#F9FAFB',
                editable: false,
            },
            {
                id: 'title-1',
                type: 'text',
                content: 'Our Proven Process',
                x: 960,
                y: 100,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'step-1',
                type: 'text',
                content: '01\nDiscover\nWe listen',
                x: 300,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Step 1',
            },
            {
                id: 'step-2',
                type: 'text',
                content: '02\nDesign\nWe create',
                x: 900,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Step 2',
            },
            {
                id: 'step-3',
                type: 'text',
                content: '03\nDeliver\nWe launch',
                x: 1500,
                y: 300,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#0F172A',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Step 3',
            },
        ],
    },
    {
        id: 'agency-cta',
        name: 'Start Project',
        category: 'agency',
        size: { width: 1920, height: 1080 },
        thumbnail: '🚀',
        description: 'Project inquiry CTA',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#3B82F6', '#1D4ED8'],
                },
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'Let\'s Build Something Amazing',
                x: 960,
                y: 300,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Get a free project quote in 24 hours',
                x: 960,
                y: 450,
                fontSize: 28,
                fontFamily: 'Arial',
                color: '#BFDBFE',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Subheadline',
            },
            {
                id: 'email-form-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 660,
                y: 600,
                width: 600,
                height: 140,
                color: '#FFFFFF',
                cornerRadius: 12,
                editable: false,
                shadow: { blur: 20, color: 'rgba(0,0,0,0.2)' },
            },
            {
                id: 'email-field-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 630,
                width: 520,
                height: 50,
                color: '#F3F4F6',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'email-placeholder',
                type: 'text',
                content: 'Enter your email to get started...',
                x: 720,
                y: 655,
                fontSize: 18,
                fontFamily: 'Arial',
                color: '#9CA3AF',
                editable: true,
                editLabel: '📝 Email Placeholder',
            },
            {
                id: 'submit-btn-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 700,
                width: 520,
                height: 50,
                color: '#1D4ED8',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'submit-btn-text',
                type: 'text',
                content: 'Get My Free Quote',
                x: 960,
                y: 725,
                fontSize: 18,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Submit Button Text',
            },
        ],
    },

    // ========================================
    // LEAD MAGNET TEMPLATES (5)
    // ========================================
    {
        id: 'lead-ebook',
        name: 'Free eBook',
        category: 'leadmagnet',
        size: { width: 1920, height: 1080 },
        thumbnail: '📚',
        description: 'Download lead magnet',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#FEF3C7',
                editable: false,
            },
            {
                id: 'badge',
                type: 'text',
                content: 'FREE DOWNLOAD',
                x: 960,
                y: 150,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#92400E',
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'The Complete Guide to Growing Your Business Online',
                x: 960,
                y: 250,
                fontSize: 48,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#78350F',
                textAlign: 'center',
                maxWidth: 900,
                editable: true,
                editLabel: '📝 Title',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: '50+ pages of proven strategies • Instant download',
                x: 960,
                y: 450,
                fontSize: 20,
                fontFamily: 'Arial',
                color: '#92400E',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Subheadline',
            },
            {
                id: 'email-form-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 660,
                y: 650,
                width: 600,
                height: 120,
                color: '#FFFFFF',
                cornerRadius: 12,
                editable: false,
                shadow: { blur: 20, color: 'rgba(0,0,0,0.1)' },
            },
            {
                id: 'email-field-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 680,
                width: 400,
                height: 50,
                color: '#F3F4F6',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'email-placeholder',
                type: 'text',
                content: 'Enter your email address...',
                x: 720,
                y: 705,
                fontSize: 18,
                fontFamily: 'Arial',
                color: '#9CA3AF',
                editable: true,
                editLabel: '📝 Email Placeholder',
            },
            {
                id: 'submit-btn-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 1120,
                y: 680,
                width: 120,
                height: 50,
                color: '#3B82F6',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'submit-btn-text',
                type: 'text',
                content: 'Get It Free',
                x: 1180,
                y: 705,
                fontSize: 16,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Submit Button Text',
            },
        ],
    },
    {
        id: 'lead-webinar',
        name: 'Webinar Signup',
        category: 'leadmagnet',
        size: { width: 1920, height: 1080 },
        thumbnail: '🎥',
        description: 'Live training registration',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#7C3AED', '#C026D3'],
                },
                editable: false,
            },
            {
                id: 'badge',
                type: 'text',
                content: 'LIVE TRAINING',
                x: 960,
                y: 150,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FCD34D',
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'How to 10X Your Revenue in 90 Days',
                x: 960,
                y: 250,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Thursday, Jan 15th at 2 PM EST • Limited Seats',
                x: 960,
                y: 400,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#E9D5FF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Date & Time',
            },
            {
                id: 'email-form-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 660,
                y: 550,
                width: 600,
                height: 140,
                color: '#FFFFFF',
                cornerRadius: 12,
                editable: false,
                shadow: { blur: 20, color: 'rgba(0,0,0,0.2)' },
            },
            {
                id: 'email-field-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 580,
                width: 520,
                height: 50,
                color: '#F3F4F6',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'email-placeholder',
                type: 'text',
                content: 'Enter your best email address...',
                x: 720,
                y: 605,
                fontSize: 18,
                fontFamily: 'Arial',
                color: '#9CA3AF',
                editable: true,
                editLabel: '📝 Email Placeholder',
            },
            {
                id: 'submit-btn-bg',
                type: 'shape',
                shape: 'roundedRect',
                x: 700,
                y: 650,
                width: 520,
                height: 50,
                color: '#10B981',
                cornerRadius: 8,
                editable: false,
            },
            {
                id: 'submit-btn-text',
                type: 'text',
                content: 'Reserve My Seat Now',
                x: 960,
                y: 675,
                fontSize: 18,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Submit Button Text',
            },
        ],
    },
    {
        id: 'lead-checklist',
        name: 'Free Checklist',
        category: 'leadmagnet',
        size: { width: 1920, height: 1080 },
        thumbnail: '✅',
        description: 'Actionable checklist download',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#ECFDF5',
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'Get Your FREE Success Checklist',
                x: 960,
                y: 300,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#065F46',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: '25 proven steps to grow your business',
                x: 960,
                y: 450,
                fontSize: 28,
                fontFamily: 'Arial',
                color: '#047857',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Subheadline',
            },
        ],
    },
    {
        id: 'lead-template',
        name: 'Template Pack',
        category: 'leadmagnet',
        size: { width: 1920, height: 1080 },
        thumbnail: '📝',
        description: 'Ready-to-use templates',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                color: '#EFF6FF',
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: '50 Templates That Convert',
                x: 960,
                y: 300,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#1E40AF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Email templates, sales pages, ad copy and more',
                x: 960,
                y: 450,
                fontSize: 28,
                fontFamily: 'Arial',
                color: '#3B82F6',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Subheadline',
            },
        ],
    },
    {
        id: 'lead-video',
        name: 'Video Training',
        category: 'leadmagnet',
        size: { width: 1920, height: 1080 },
        thumbnail: '▶️',
        description: 'On-demand video course',
        elements: [
            {
                id: 'bg-1',
                type: 'background',
                gradient: {
                    type: 'linear',
                    angle: 135,
                    colors: ['#EF4444', '#DC2626'],
                },
                editable: false,
            },
            {
                id: 'badge',
                type: 'text',
                content: 'FREE VIDEO COURSE',
                x: 960,
                y: 150,
                fontSize: 24,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FEE2E2',
                textAlign: 'center',
                editable: false,
            },
            {
                id: 'headline-1',
                type: 'text',
                content: 'Master Facebook Ads in 7 Days',
                x: 960,
                y: 250,
                fontSize: 56,
                fontWeight: 'bold',
                fontFamily: 'Arial',
                color: '#FFFFFF',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Headline',
            },
            {
                id: 'subheadline-1',
                type: 'text',
                content: 'Step-by-step video training • 3 hours of content',
                x: 960,
                y: 400,
                fontSize: 24,
                fontFamily: 'Arial',
                color: '#FECACA',
                textAlign: 'center',
                editable: true,
                editLabel: '📝 Subheadline',
            },
        ],
    },
];

export const TEMPLATE_CATEGORIES = [
    { id: 'saas', name: 'SaaS', icon: '💼', count: 5 },
    { id: 'ecommerce', name: 'E-commerce', icon: '🛍️', count: 5 },
    { id: 'coaching', name: 'Coaching', icon: '🎓', count: 5 },
    { id: 'agency', name: 'Agency', icon: '🎨', count: 5 },
    { id: 'leadmagnet', name: 'Lead Magnets', icon: '🎁', count: 5 },
];